name: Publish Package to npmjs
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v7
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - run: yarn
      - run: yarn sdk-ts
      - run: cd sdk/ts && node -e 'const json=require("./package.json");fs.writeFileSync("./package.json",JSON.stringify({...json, version:process.env.GITHUB_REF?.replace("refs/tags/", "")}, undefined, 2), "utf-8")' && cat package.json && yarn && yarn build && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  coverage:
    permissions:
      contents: read
      checks: write   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2