name: Publish Package to npmjs
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v7
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - run: yarn
      - run: yarn sdk-ts
      - run: cd sdk/ts && node -e 'const json=require("./package.json");fs.writeFileSync("./package.json",JSON.stringify({...json, version:process.env.GITHUB_REF?.replace("refs/tags/", "")}, undefined, 2), "utf-8")' && cat package.json && yarn && yarn build && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  coverage:
    permissions:
      contents: read
      checks: write   
      pull-requests: write   # Required to comment on PRs
    runs-on: ubuntu-latest
    steps:
      - name: Generate Jest Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage_report
        with:
          output: report-markdown # Generates markdown instead of a PR comment
          skip-step: none

      - name: Append Coverage to Release Body
        uses: actions/github-script@v7
        env:
          REPORT: ${{ steps.coverage_report.outputs.report }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const release_id = context.payload.release.id;
            const originalBody = context.payload.release.body || "";
            
            // Build the collapsible coverage section
            const coverageSection = `
            
            <details>
            <summary>📊 View Jest Test Coverage Report</summary>
            
            ${process.env.REPORT}
            
            </details>
            `;
            
            // Update the release body on GitHub
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id,
              body: originalBody + coverageSection
            });